


POST   http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content" : "jyhtdrffjhgdf",
    "important": true
}
###
GET http://localhost:3001/api/notes/
###
DELETE http://localhost:3001/api/notes/6093e0e739c92c26cd2c0fef


