


POST   http://localhost:3001/api/notes
Content-Type: application/json
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvdW90IiwiaWQiOiI2MGVlZTY5ZmZlZjhkNjU1ODM1ZDgzZTYiLCJpYXQiOjE2MjYyNjkzODV9.NnZtnJTLh9wmzb01A-iSMv5oQBQ4Qg6MnLAHYQ3FdaY

{

    "content" : "usehituyukrfghjnotes",
    "important": true
   
}

###
GET http://localhost:3001/api/notes/
###
DELETE http://localhost:3001/api/notes/


###
POST   http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes": [],
    "username": "rouot",
    "name": "user",
    "password": "lainen"
}

###
GET http://localhost:3001/api/users/

###
POST   http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "rouot",
    "password": "lainen"
}